# nodes/dataloader/qvd_field_description_node.py

"""
QVD Field Description Node
~~~~~~~~~~~~~~~~~~~~~~~~~~
This node reads a QVD file, extracts its field definitions from the XML
header, writes a YAML file mapping each field name to a description, and
generates a Python DTO module (e.g. apf_dto.py) with ColumnClass definitions.

Inputs (via shared state):
- ``qvd_path`` (str or Path): Path to the source QVD file.
- ``output_yaml_path`` (optional, str or Path): Desired location for the
  generated YAML file. If omitted, ``<qvd_stem>_fields.yaml`` next to the QVD.
- ``output_dto_path`` (optional, str or Path): Desired location for the
  generated DTO Python file. If omitted, ``data/classes/dtos/<qvd_stem>_dto.py``.

Outputs (via shared state):
- ``field_description_yaml``: Path to the generated YAML file.
- ``field_description_dto``: Path to the generated DTO Python file.
- ``file_description``: LLM-generated description of the file and data content.
"""

from __future__ import annotations

import re
import unicodedata
from pathlib import Path
from typing import Any, Dict, List, Optional

import yaml

from nodes.base_node import BaseNode
from monitoring.logger import get_logger
from llm.llm_factory import get_llm
from config import get_settings

logger = get_logger(__name__)


def get_file_description(
    qvd_path: str | Path,
    field_names: List[str],
    descriptions: Optional[Dict[str, str]] = None,
) -> str:
    """
    Use the configured LLM to generate a file description and data content meaning.

    Args:
        qvd_path: Path to the QVD file (used for context, e.g. filename).
        field_names: List of column/field names in the file.
        descriptions: Optional mapping of field name -> description.

    Returns:
        A human-readable description of the file and what its data represents.
    """
    llm_client, _ = get_llm()
    model = get_settings().llm.model

    stem = Path(qvd_path).stem
    fields_text = "\n".join(
        f"- {name}: {descriptions.get(name, '(no description)')}"
        for name in field_names
    ) if descriptions else "\n".join(f"- {name}" for name in field_names)

    from prompt_loader import render_template
    prompt = render_template(
        "dataloader", "qvd_field_description",
        file_stem=stem,
        fields_text=fields_text,
    )

    try:
        response = llm_client.chat.completions.create(
            model=model,
            messages=[{"role": "user", "content": prompt}],
        )
        return (response.choices[0].message.content or "").strip()
    except Exception as e:
        logger.warning("LLM file description failed for %s: %s", qvd_path, e)
        return f"Data file '{stem}' with {len(field_names)} columns: {', '.join(field_names[:8])}{'...' if len(field_names) > 8 else ''}."


def _sanitize_column_name(name: str) -> str:
    """Sanitize column names for Python compatibility (matches qvd_read_node)."""
    if not name:
        return name
    sanitized = name.replace("'", "_").replace("'", "_").replace('"', "_")
    sanitized = sanitized.replace(" ", "_")
    sanitized = unicodedata.normalize("NFKD", sanitized)
    sanitized = "".join(ch for ch in sanitized if unicodedata.category(ch) != "Mn")
    sanitized = re.sub(r"[^a-zA-Z0-9_]", "", sanitized)
    sanitized = re.sub(r"_+", "_", sanitized)
    return sanitized.strip("_") or name


def _infer_type_and_categorical(column_name: str) -> tuple[str, bool]:
    """Infer ColumnClass type and is_categorical from column name."""
    name_lower = column_name.lower()
    if any(x in name_lower for x in ("total", "montant", "solde", "surface", "prix", "tva", "quantite")):
        return "float", False
    if any(x in name_lower for x in ("annee", "an", "annee")):
        return "float", False
    if any(x in name_lower for x in ("date", "jour")):
        return "datetime", False
    if any(x in name_lower for x in ("nationalite", "nationalité", "mois", "ville", "nom", "poste", "voie", "status", "mretes")):
        return "string", True
    return "string", False


def _generate_dto_python(
    stem: str,
    field_entries: list[tuple[str, str]],
    file_description: str = "",
) -> str:
    """Generate Python DTO module content. field_entries: [(sanitized_column_name, description), ...]."""
    desc_repr = repr(file_description)
    lines = [
        '"""',
        f"Column definitions for {stem.upper()} table from QVD.",
        "",
        "Auto-generated by QVDFieldDescriptionNode from QVD field descriptions.",
        '"""',
        "",
        "from classes.columns_classes import ColumnClass, ColumnsClasses",
        "",
        "",
        "def get_file_description() -> str:",
        '    """Return the file description and data content meaning."""',
        f"    return {desc_repr}",
        "",
        "",
        "def get_columns_descriptions() -> ColumnsClasses:",
        f'    """',
        f"    Get the column descriptions for the {stem.upper()} table.",
        "",
        "    Returns:",
        "        ColumnsClasses object with column definitions",
        '    """',
        "    return ColumnsClasses(",
        "        columns=[",
    ]
    seen = set()
    for col_name, desc in field_entries:
        if col_name in seen:
            continue
        seen.add(col_name)
        col_type, is_cat = _infer_type_and_categorical(col_name)
        desc_escaped = desc.replace('"', '\\"').replace("\n", " ")
        lines.append(f'            ColumnClass(')
        lines.append(f'                column_name="{col_name}",')
        lines.append(f'                description="{desc_escaped}",')
        lines.append(f'                type="{col_type}",')
        lines.append(f'                is_categorical={str(is_cat)},')
        lines.append(f'            ),')
    lines.append("        ]")
    lines.append("    )")
    return "\n".join(lines)


class QVDFieldDescriptionNode(BaseNode):
    """Extract field names from a QVD, write YAML descriptions, and generate DTO Python module."""

    def __init__(self, name: Optional[str] = None):
        super().__init__(name or "QVDFieldDescription")
        self.output_path: Optional[Path] = None
        self.dto_path: Optional[Path] = None

    # ---------------------------------------------------------------------
    # Preparation
    # ---------------------------------------------------------------------
    def prep(self, shared: Dict[str, Any]) -> Dict[str, Any]:
        """Validate the required inputs."""
        self.log_entry(shared)

        qvd_path = shared.get("qvd_path")
        if not qvd_path:
            raise ValueError(
                "QVDFieldDescriptionNode requires 'qvd_path' in shared state"
            )
        qvd_path = Path(qvd_path)
        if not qvd_path.is_file():
            raise FileNotFoundError(f"QVD file not found: {qvd_path}")

        output_yaml_path = shared.get("output_yaml_path")
        if output_yaml_path:
            output_yaml_path = Path(output_yaml_path)
        else:
            output_yaml_path = qvd_path.with_name(qvd_path.stem + "_fields.yaml")

        output_dto_path = shared.get("output_dto_path")
        if output_dto_path:
            output_dto_path = Path(output_dto_path)
        else:
            output_dto_path = Path("data/classes/dtos") / f"{qvd_path.stem}_dto.py"

        self.qvd_path = qvd_path
        self.output_path = output_yaml_path
        self.dto_path = output_dto_path

        return {
            "qvd_path": str(qvd_path),
            "output_yaml_path": str(output_yaml_path),
            "output_dto_path": str(output_dto_path),
        }

    # ---------------------------------------------------------------------
    # Execution
    # ---------------------------------------------------------------------
    def exec(self, prep_result: Dict[str, Any]) -> Dict[str, Any]:
        """Parse the QVD header, extract field names, write YAML and DTO."""
        try:
            with open(self.qvd_path, "rb") as f:
                raw = f.read(64 * 1024)
        except Exception as e:
            self.logger.error("Failed to read QVD file %s: %s", self.qvd_path, e)
            raise

        text = raw.decode("utf-8", errors="ignore")

        fields_block_match = re.search(r"<Fields>(.*?)</Fields>", text, re.DOTALL)
        if not fields_block_match:
            raise RuntimeError("Could not locate <Fields> section in QVD header")
        fields_block = fields_block_match.group(1)

        field_names = re.findall(r"<FieldName>(.*?)</FieldName>", fields_block)
        if not field_names:
            raise RuntimeError("No field names found in QVD <Fields> section")

        descriptions: Dict[str, str] = {}
        if self.output_path.is_file():
            try:
                with open(self.output_path, "r", encoding="utf-8") as f:
                    existing = yaml.safe_load(f) or {}
                for name in field_names:
                    descriptions[name] = existing.get(name, f"Description for {name}.")
            except Exception as e:
                self.logger.warning("Could not load existing YAML %s: %s", self.output_path, e)
                for name in field_names:
                    descriptions[name] = f"Description for {name}."
        else:
            for name in field_names:
                descriptions[name] = f"Description for {name}."

        yaml_content = yaml.safe_dump(descriptions, sort_keys=False, allow_unicode=True)
        try:
            self.output_path.parent.mkdir(parents=True, exist_ok=True)
            with open(self.output_path, "w", encoding="utf-8") as out:
                out.write(yaml_content)
        except Exception as e:
            self.logger.error("Failed to write YAML file %s: %s", self.output_path, e)
            raise

        self.logger.info("Wrote field description YAML to %s", self.output_path)

        field_entries: list[tuple[str, str]] = []
        for orig_name in field_names:
            col_name = _sanitize_column_name(orig_name)
            desc = descriptions.get(orig_name, f"Description for {orig_name}.")
            field_entries.append((col_name, desc))

        file_description = get_file_description(
            self.qvd_path, field_names, descriptions
        )
        self.logger.info("Generated file description via LLM")

        dto_content = _generate_dto_python(
            self.qvd_path.stem, field_entries, file_description
        )
        try:
            self.dto_path.parent.mkdir(parents=True, exist_ok=True)
            with open(self.dto_path, "w", encoding="utf-8") as out:
                out.write(dto_content)
        except Exception as e:
            self.logger.error("Failed to write DTO file %s: %s", self.dto_path, e)
            raise

        self.logger.info("Wrote DTO module to %s", self.dto_path)

        return {
            "yaml_path": str(self.output_path),
            "dto_path": str(self.dto_path),
            "field_count": len(field_names),
            "file_description": file_description,
        }

    # ---------------------------------------------------------------------
    # Post‑processing
    # ---------------------------------------------------------------------
    def post(
        self,
        shared: Dict[str, Any],
        prep_result: Dict[str, Any],
        exec_result: Dict[str, Any],
    ) -> str:
        """Record the generated paths and file description in shared state and finish."""
        shared["field_description_yaml"] = exec_result["yaml_path"]
        shared["field_description_dto"] = exec_result["dto_path"]
        shared["file_description"] = exec_result.get("file_description", "")
        self.log_exit("end")
        return "end"


if __name__ == "__main__":
    qvd = Path("data/raw/apf.qvd") if Path("data/raw/apf.qvd").exists() else Path("data/raw/arriver.qvd")
    dto_path = Path("data/classes/dtos") / f"{qvd.stem}_dto.py"
    node = QVDFieldDescriptionNode()
    shared = {
        "qvd_path": str(qvd),
        "output_dto_path": str(dto_path),
    }
    prep_result = node.prep(shared)
    exec_result = node.exec(prep_result)
    node.post(shared, prep_result, exec_result)

    print("\nFile description:")
    print(shared.get("file_description", "(none)"))
    