# nodes/dataloader/xlsx_field_description_node.py

"""
XLSX Field Description Node
~~~~~~~~~~~~~~~~~~~~~~~~~~~
Reads the schema (column names + dtypes) of a parquet file produced by the
XLSX → Parquet pipeline and generates:

1. A YAML field-description sidecar (``<source_id>_fields.yaml``).
2. A Python DTO module under ``data/classes/dtos/<source_id>_dto.py``.

This mirrors :class:`nodes.dataloader.qvd_field_description_node.QVDFieldDescriptionNode`
but operates on the *post-pipeline* parquet (which already has sanitised
column names) rather than on a binary QVD header.

The node intentionally does **not** call an LLM to keep XLSX uploads
fast and deterministic.  A simple deterministic file description is
generated from the column list and can be hand-edited later by the user.

Inputs (via shared state):
- ``parquet_path``       (str | Path):   Source parquet file (post pipeline).
- ``source_id``          (str):          Identifier used for the DTO stem.
- ``output_yaml_path``   (str | Path, optional)
- ``output_dto_path``    (str | Path, optional)

Outputs (via shared state):
- ``field_description_yaml`` (str): Path to the YAML written.
- ``field_description_dto``  (str): Path to the DTO Python module.
- ``columns_class``          (str): Importable dotted path
                                    (e.g. ``classes.dtos.balance_xlsx_dto``).
- ``file_description``       (str): Auto-generated description.
"""

from __future__ import annotations

import re
from pathlib import Path
from typing import Any, Dict, List, Optional, Tuple

import pyarrow.parquet as pq
import yaml

from monitoring.logger import get_logger
from nodes.base_node import BaseNode

logger = get_logger(__name__)


# ---------------------------------------------------------------------------
# Type / categorical inference helpers
# ---------------------------------------------------------------------------

# Cardinality threshold used to flag string columns as categorical without a
# full-table scan.  We keep it cheap: any string column that *also* has a
# name suggestive of a category gets flagged.
_CATEGORICAL_HINT_RE = re.compile(
    r"(?:^|_)(?:type|status|statut|categ|category|categorie|class|classe|"
    r"genre|sex|sexe|country|pays|nationalite|nationality|region|"
    r"departement|department|ville|city|client|product|produit|"
    r"agence|branch|libelle|code|etat|state|kind|level|niveau|"
    r"famille|family|brand|marque|currency|devise|month|mois)(?:_|$)",
    re.IGNORECASE,
)


def _arrow_type_to_column_type(arrow_type) -> str:
    """Map a pyarrow type to one of the ``ColumnClass.type`` values.

    Returns one of: ``string``, ``integer``, ``float``, ``boolean``, ``date``,
    ``datetime``.  Falls back to ``string`` for unknown types so downstream
    Pydantic validation never trips.
    """
    s = str(arrow_type).lower()
    if "bool" in s:
        return "boolean"
    if "timestamp" in s:
        return "datetime"
    if s == "date32" or s == "date64" or "date" in s:
        return "date"
    if s.startswith("int") or s.startswith("uint") or "int8" in s or "int16" in s or "int32" in s or "int64" in s:
        return "integer"
    if s.startswith("float") or s.startswith("double") or "decimal" in s or "halffloat" in s:
        return "float"
    return "string"


def _is_categorical(column_name: str, col_type: str) -> bool:
    """Heuristic: only string-typed columns whose name matches a categorical
    hint are flagged.  Numeric / temporal columns are never categorical."""
    if col_type != "string":
        return False
    return bool(_CATEGORICAL_HINT_RE.search(column_name or ""))


# ---------------------------------------------------------------------------
# DTO file generator
# ---------------------------------------------------------------------------

def _generate_dto_python(
    stem: str,
    field_entries: List[Tuple[str, str, str, bool]],
    file_description: str = "",
) -> str:
    """Render the Python DTO module.

    Args:
        stem:              Module / table identifier (e.g. ``balance_xlsx``).
        field_entries:     List of ``(column_name, description, type, is_categorical)``
                           tuples.  Caller is responsible for de-duplication.
        file_description:  Free-text describing the file at a high level.
    """
    desc_repr = repr(file_description)
    lines: List[str] = [
        '"""',
        f"Column definitions for {stem.upper()} table from XLSX upload.",
        "",
        "Auto-generated by XLSXFieldDescriptionNode from the post-pipeline",
        "parquet schema.  Edit freely to refine descriptions or",
        "categorical flags before running the embedding generation step.",
        '"""',
        "",
        "from classes.columns_classes import ColumnClass, ColumnsClasses",
        "",
        "",
        "def get_file_description() -> str:",
        '    """Return the file description and data content meaning."""',
        f"    return {desc_repr}",
        "",
        "",
        "def get_columns_descriptions() -> ColumnsClasses:",
        '    """',
        f"    Get the column descriptions for the {stem.upper()} table.",
        "",
        "    Returns:",
        "        ColumnsClasses object with column definitions",
        '    """',
        "    return ColumnsClasses(",
        "        columns=[",
    ]

    seen: set[str] = set()
    for col_name, desc, col_type, is_cat in field_entries:
        if col_name in seen:
            continue
        seen.add(col_name)
        desc_escaped = desc.replace('"', '\\"').replace("\n", " ")
        lines.append("            ColumnClass(")
        lines.append(f'                column_name="{col_name}",')
        lines.append(f'                description="{desc_escaped}",')
        lines.append(f'                type="{col_type}",')
        lines.append(f"                is_categorical={str(is_cat)},")
        lines.append("            ),")

    lines.append("        ]")
    lines.append("    )")
    return "\n".join(lines) + "\n"


# ---------------------------------------------------------------------------
# Public helper (used by API route, tests, and the Node alike)
# ---------------------------------------------------------------------------

def generate_xlsx_dto(
    parquet_path: str | Path,
    *,
    source_id: str,
    output_dto_path: Optional[str | Path] = None,
    output_yaml_path: Optional[str | Path] = None,
    project_root: Optional[Path] = None,
) -> Dict[str, Any]:
    """Generate a DTO module + YAML sidecar from a parquet file's schema.

    Returns a dict with the keys ``yaml_path``, ``dto_path``, ``columns_class``,
    ``file_description`` and ``field_count``.  Safe to call multiple times —
    overwrites existing artefacts with fresh schema-derived content.
    """
    parquet_path = Path(parquet_path)
    if not parquet_path.is_file():
        raise FileNotFoundError(f"Parquet file not found: {parquet_path}")

    if project_root is None:
        # nodes/dataloader/xlsx_field_description_node.py  →  parents[2] = brikz-agent
        project_root = Path(__file__).resolve().parents[2]

    schema = pq.ParquetFile(parquet_path).schema_arrow
    field_names: List[str] = [f.name for f in schema]
    field_types: List[str] = [_arrow_type_to_column_type(f.type) for f in schema]
    if not field_names:
        raise RuntimeError(f"Parquet has no columns: {parquet_path}")

    yaml_path = (
        Path(output_yaml_path)
        if output_yaml_path
        else project_root / "data" / f"{source_id}_fields.yaml"
    )
    dto_path = (
        Path(output_dto_path)
        if output_dto_path
        else project_root / "data" / "classes" / "dtos" / f"{source_id}_dto.py"
    )

    descriptions: Dict[str, str] = {}
    if yaml_path.is_file():
        try:
            existing = yaml.safe_load(yaml_path.read_text(encoding="utf-8")) or {}
            if isinstance(existing, dict):
                descriptions.update(
                    {k: str(v) for k, v in existing.items() if isinstance(k, str)}
                )
        except Exception as exc:
            logger.warning(
                "Could not load existing XLSX YAML %s: %s", yaml_path, exc
            )

    # Fill in placeholders for any column missing a description so the YAML is
    # always complete and editable.
    for name in field_names:
        descriptions.setdefault(name, f"Description for {name}.")

    yaml_path.parent.mkdir(parents=True, exist_ok=True)
    yaml_path.write_text(
        yaml.safe_dump(descriptions, sort_keys=False, allow_unicode=True),
        encoding="utf-8",
    )

    field_entries: List[Tuple[str, str, str, bool]] = []
    for name, col_type in zip(field_names, field_types):
        desc = descriptions.get(name, f"Description for {name}.")
        is_cat = _is_categorical(name, col_type)
        field_entries.append((name, desc, col_type, is_cat))

    file_description = (
        f"Excel-derived dataset '{source_id}' with {len(field_names)} columns: "
        + ", ".join(field_names[:8])
        + ("..." if len(field_names) > 8 else "")
        + "."
    )

    dto_content = _generate_dto_python(source_id, field_entries, file_description)
    dto_path.parent.mkdir(parents=True, exist_ok=True)
    dto_path.write_text(dto_content, encoding="utf-8")

    # Build the importable dotted path expected by datasources.yaml /
    # ``columns_class``.  DTO modules live under ``<project_root>/data`` so
    # the rest of the codebase imports them via ``classes.dtos.<stem>``
    # (``data`` is added to ``sys.path`` at startup by the DTO cache flow).
    try:
        rel = dto_path.resolve().relative_to((project_root / "data").resolve())
    except ValueError:
        try:
            rel = dto_path.resolve().relative_to(project_root.resolve())
        except ValueError:
            rel = dto_path
    # Always emit the *explicit* ``module.path:function_name`` form so the
    # value works with strict consumers (XLSXConnector, CSVConnector,
    # SQLServer/Oracle/Supabase connectors) which all require the colon.
    # The looser ``module.path`` form is still handled by the XLSX connector
    # for backwards-compat with manually-edited datasources.yaml entries.
    module_dotted = (
        str(rel.with_suffix("")).replace("/", ".").replace("\\", ".")
    )
    columns_class = f"{module_dotted}:get_columns_descriptions"

    logger.info(
        "Generated XLSX DTO for '%s' (%d columns) → %s",
        source_id,
        len(field_names),
        dto_path,
    )

    return {
        "yaml_path": str(yaml_path),
        "dto_path": str(dto_path),
        "columns_class": columns_class,
        "file_description": file_description,
        "field_count": len(field_names),
    }


# ---------------------------------------------------------------------------
# PocketFlow Node
# ---------------------------------------------------------------------------

class XLSXFieldDescriptionNode(BaseNode):
    """Generate a DTO + YAML from a parquet file produced by the XLSX
    pipeline.  Designed to run *after* ``ParquetWriterNode``."""

    def __init__(self, name: Optional[str] = None):
        super().__init__(name or "XLSXFieldDescription")

    def prep(self, shared: Dict[str, Any]) -> Dict[str, Any]:
        self.log_entry(shared)

        parquet_path: Optional[str] = shared.get("parquet_path")
        if not parquet_path:
            write_results = shared.get("parquet_write_results") or []
            if write_results:
                parquet_path = write_results[0].get("filename")
        if not parquet_path:
            parquet_path = shared.get("parquet_output")
        if not parquet_path:
            raise ValueError(
                "XLSXFieldDescriptionNode requires 'parquet_path', "
                "'parquet_write_results' or 'parquet_output' in shared state"
            )

        source_id: Optional[str] = shared.get("source_id")
        if not source_id:
            source_id = Path(str(parquet_path)).stem

        return {
            "parquet_path": str(parquet_path),
            "source_id": source_id,
            "output_yaml_path": shared.get("output_yaml_path"),
            "output_dto_path": shared.get("output_dto_path"),
        }

    def exec(self, prep_result: Dict[str, Any]) -> Dict[str, Any]:
        return generate_xlsx_dto(
            prep_result["parquet_path"],
            source_id=prep_result["source_id"],
            output_dto_path=prep_result.get("output_dto_path"),
            output_yaml_path=prep_result.get("output_yaml_path"),
        )

    def post(
        self,
        shared: Dict[str, Any],
        prep_result: Dict[str, Any],
        exec_result: Dict[str, Any],
    ) -> str:
        shared["field_description_yaml"] = exec_result["yaml_path"]
        shared["field_description_dto"] = exec_result["dto_path"]
        shared["columns_class"] = exec_result["columns_class"]
        shared["file_description"] = exec_result.get("file_description", "")
        self.log_exit("default")
        return "default"


if __name__ == "__main__":
    import argparse

    parser = argparse.ArgumentParser(description="Generate a DTO from an XLSX-derived parquet")
    parser.add_argument("parquet", type=str, help="Path to the parquet file")
    parser.add_argument("--source-id", type=str, required=True)
    args = parser.parse_args()

    out = generate_xlsx_dto(args.parquet, source_id=args.source_id)
    print(out)
