"""
SQL Thinking Flow — Iterative query → execute → evaluate loop with semantic resolution.

Orchestrates the thinking pipeline:

    ┌─────────────────────────────────────────────────────────────────────┐
    │                                                                     │
    │  ┌──────────┐    ┌─────────┐    ┌───────────┐    ┌────────────┐    │
    │  │ Semantic  │──▶│ SQL Gen  │──▶│ SQL Exec  │──▶│ Evaluation  │──▶ done
    │  │ Resolver  │    └─────────┘    └───────────┘    └────────────┘    │
    │  └──────────┘         ▲                               │ insufficient│
    │                       │         ┌──────────────┐      │             │
    │                       └─────────│ RefineGuard  │◀─────┘             │
    │                                 └──────────────┘                    │
    └─────────────────────────────────────────────────────────────────────┘

Streaming
─────────
Pass ``stream_callback`` to ``run_sql_thinking()`` (or set
``shared["stream_callback"]``) to receive real-time updates.

The callback signature is ``Callable[[str, str, dict | None], None]``:
    stream_callback(event_type, message, data=None)

Event types emitted:
  ``thinking``         — high-level status message (always streamed)
  ``semantic_match``   — an entity was resolved via embedding similarity
  ``sql_generated``    — SQL queries were generated by the LLM
  ``sql_result``       — a query returned results
  ``evaluation``       — evaluation score and verdict
  ``iteration``        — a new refinement iteration starts
  ``complete``         — final results ready
  ``error``            — an error occurred

Shared-state contract (caller must provide):
──────────────────────────────────────────────
  Required:
      query             (str)  — natural-language question

  Optional:
      session_id        (str)  — conversation session id (default: "default")
      stream_callback   (callable) — streaming callback (see above)
      prior_response_data (Any) — seed context from a prior interaction
      sql_results       (list[dict]) — seed results from a prior execution
      parquet_cache_dir (str)  — override parquet directory
      sql_max_rows      (int)  — cap rows per query (default 500)
      evaluation_threshold (float) — score threshold (default 0.7)
      max_iterations    (int)  — max generate→execute→evaluate loops (default 3)

  Outputs (after flow completes):
      sql_queries          (list[dict])  — final generated queries
      sql_results          (list[dict])  — final execution results
      sql_results_summary  (str)         — human-readable summary
      evaluation           (dict)        — final evaluation score + details
      semantic_results     (list[dict])  — resolved entity matches (if any)
      iteration_count      (int)         — number of loops executed
      iteration_history    (list[dict])  — score per iteration
"""

from __future__ import annotations

import yaml
from pathlib import Path
from typing import Any, Callable, Dict, List, Optional

from pocketflow import Flow, Node as PFNode

from nodes.thinking.sql_generation_node import SQLGenerationNode
from nodes.thinking.sql_execution_node import SQLExecutionNode
from nodes.thinking.response_evaluation_node import ResponseEvaluationNode
from nodes.dataloader.semantic_search_node import (
    SemanticSearchNode,
    DEFAULT_EMBEDDING_MODEL,
)
from llm.llm_factory import get_llm
from config import get_settings
from config.settings import settings as pydantic_settings
from skill_registry import load_skill_definitions, build_selected_skills_context

from monitoring.logger import get_logger
from services.query_cache import get_query_cache

logger = get_logger(__name__)

_DEFAULT_THRESHOLD = 0.7
_DEFAULT_MAX_ITERATIONS = 2
_SCORE_PLATEAU_TOLERANCE = 0.05
_SEMANTIC_SIMILARITY_THRESHOLD = 0.35
_SEMANTIC_TOP_K = 5

StreamCallback = Callable[[str, str, Optional[Dict[str, Any]]], None]


def _emit(shared: Dict[str, Any], event: str, message: str, data: Optional[Dict[str, Any]] = None) -> None:
    """Call the stream callback if one is registered in shared state."""
    cb = shared.get("stream_callback")
    if cb is not None:
        try:
            cb(event, message, data)
        except Exception as exc:
            logger.warning("stream_callback error (%s): %s", event, exc)


from prompt_loader import load_template


def _get_prompt(name: str) -> str:
    return load_template("sql_thinking", name)


_QUERY_CLASSIFIER_PROMPT = _get_prompt("query_classifier")
_STRATEGIC_RESPONSE_PROMPT = _get_prompt("strategic_response")
_KNOWLEDGE_ONLY_PROMPT = _get_prompt("knowledge_only")
_ENTITY_EXTRACTION_PROMPT = _get_prompt("entity_extraction")


def _discover_distinct_parquets(parquet_dir: Path) -> List[Path]:
    """Find all ``*_distinct.parquet`` files in the parquet directory."""
    if not parquet_dir.is_dir():
        return []
    return sorted(parquet_dir.glob("*_distinct.parquet"))


def _extract_entities(query: str) -> List[Dict[str, str]]:
    """Use the LLM to detect entity mentions in the user query."""
    sync_client, _ = get_llm()
    model = get_settings().llm.model

    response = sync_client.chat.completions.create(
        model=model,
        messages=[
            {"role": "system", "content": _ENTITY_EXTRACTION_PROMPT},
            {"role": "user", "content": query},
        ],
    )
    raw = response.choices[0].message.content or ""
    try:
        yaml_str = raw.split("```yaml")[1].split("```")[0].strip() if "```yaml" in raw else raw
        parsed = yaml.safe_load(yaml_str)
        entities = parsed.get("entities", [])
        if not isinstance(entities, list):
            return []
        return [e for e in entities if isinstance(e, dict) and e.get("text")]
    except Exception as exc:
        logger.warning("Entity extraction parse error: %s", exc)
        return []


def _classify_query(query: str) -> Dict[str, str]:
    """Use the LLM to classify the query type."""
    sync_client, _ = get_llm()
    model = get_settings().llm.model

    response = sync_client.chat.completions.create(
        model=model,
        messages=[
            {"role": "system", "content": _QUERY_CLASSIFIER_PROMPT},
            {"role": "user", "content": query},
        ],
    )
    raw = response.choices[0].message.content or ""
    try:
        yaml_str = raw.split("```yaml")[1].split("```")[0].strip() if "```yaml" in raw else raw
        parsed = yaml.safe_load(yaml_str)
        if not isinstance(parsed, dict):
            return {"query_type": "data_query", "reason": "Classification failed — defaulting to data_query"}
        qt = str(parsed.get("query_type", "data_query")).lower().strip()
        if qt not in ("data_query", "strategic", "knowledge_only"):
            qt = "data_query"
        return {
            "query_type": qt,
            "reason": str(parsed.get("reason", "")),
            "data_queries_needed": str(parsed.get("data_queries_needed", "")),
        }
    except Exception as exc:
        logger.warning("Query classification parse error: %s", exc)
        return {"query_type": "data_query", "reason": f"Parse error: {exc}"}


class _QueryClassifierNode(PFNode):
    """Classifies the user query to decide the flow route.

    Returns:
      - "data_query" → standard SQL pipeline (semantic → sql_gen → exec → eval)
      - "strategic"  → SQL pipeline then strategic synthesis
      - "knowledge_only" → direct LLM answer using skills (no SQL)
    """

    def prep(self, shared):
        _emit(shared, "thinking", "Analyse du type de requête…")
        return shared.get("query", "")

    def exec(self, query):
        return _classify_query(query)

    def post(self, shared, prep_res, exec_res):
        query_type = exec_res.get("query_type", "data_query")
        shared["query_type"] = query_type
        shared["query_classification"] = exec_res

        logger.info(
            "Query classified as '%s': %s",
            query_type, exec_res.get("reason", ""),
        )

        if query_type == "strategic":
            if exec_res.get("data_queries_needed"):
                shared["strategic_data_hint"] = exec_res["data_queries_needed"]
            _emit(shared, "thinking",
                  "Requête stratégique détectée — collecte de données puis synthèse stratégique…")
            return "data_query"

        if query_type == "knowledge_only":
            _emit(shared, "thinking",
                  "Question de connaissances métier — réponse directe depuis l'expertise…")
            return "knowledge_only"

        _emit(shared, "thinking", "Requête de données — lancement de l'analyse SQL…")
        return "data_query"


class _KnowledgeOnlyNode(PFNode):
    """Answers knowledge-only queries using skills context without SQL."""

    def prep(self, shared):
        return {
            "query": shared.get("query", ""),
            "skills_context": shared.get("skills_context", ""),
        }

    def exec(self, prep_res):
        query = prep_res["query"]
        skills_context = prep_res["skills_context"]

        sync_client, _ = get_llm()
        model = get_settings().llm.model

        system_parts = [_KNOWLEDGE_ONLY_PROMPT]
        if skills_context:
            system_parts.append(f"\n## Expertise métier\n\n{skills_context}")

        response = sync_client.chat.completions.create(
            model=model,
            messages=[
                {"role": "system", "content": "\n".join(system_parts)},
                {"role": "user", "content": query},
            ],
        )
        return response.choices[0].message.content or ""

    def post(self, shared, prep_res, exec_res):
        shared["strategic_response"] = exec_res
        shared["response_type"] = "knowledge_only"
        shared["evaluation"] = {
            "precision_score": 1.0,
            "verdict": "excellent",
            "justification": "Réponse basée sur l'expertise métier (pas de données SQL nécessaires).",
            "missing": [],
            "suggestions": [],
        }
        _emit(shared, "thinking", "Réponse basée sur l'expertise métier générée.")
        return "default"


class _StrategicResponseNode(PFNode):
    """Synthesizes SQL data results + skills into a rich strategic response.

    For 'strategic' queries: generates a full strategic synthesis.
    For 'data_query' queries: passes through without synthesis.
    Also handles error/empty fallback for strategic queries.
    """

    def prep(self, shared):
        query_type = shared.get("query_type", "data_query")
        if query_type != "strategic":
            shared["response_type"] = "data_query"
            return None

        _emit(shared, "thinking", "Synthèse stratégique en cours — combinaison des données et de l'expertise…")
        from nodes.thinking.sql_generation_node import _format_sql_results

        return {
            "query": shared.get("query", ""),
            "skills_context": shared.get("skills_context", ""),
            "sql_results": shared.get("sql_results", []),
            "sql_results_summary": shared.get("sql_results_summary", ""),
            "sql_queries": shared.get("sql_queries", []),
            "formatted_results": _format_sql_results(shared.get("sql_results", [])),
        }

    def exec(self, prep_res):
        if prep_res is None:
            return None

        query = prep_res["query"]
        skills_context = prep_res["skills_context"]
        formatted_results = prep_res["formatted_results"]
        sql_results_summary = prep_res["sql_results_summary"]

        sync_client, _ = get_llm()
        model = get_settings().llm.model

        system_parts = [_STRATEGIC_RESPONSE_PROMPT]
        if skills_context:
            system_parts.append(f"\n## Expertise métier (KPIs, formules, benchmarks)\n\n{skills_context}")

        user_parts = [f"## Question de l'utilisateur\n\n{query}"]

        if formatted_results:
            user_parts.append(
                f"\n## Données disponibles (issues de l'analyse SQL)\n\n{formatted_results}"
            )
        if sql_results_summary:
            user_parts.append(f"\n## Résumé des résultats\n\n{sql_results_summary}")

        if not formatted_results and not sql_results_summary:
            user_parts.append(
                "\n## Note\n\nAucune donnée SQL spécifique n'a pu être extraite. "
                "Base ta réponse sur ton expertise métier et les benchmarks internationaux."
            )

        response = sync_client.chat.completions.create(
            model=model,
            messages=[
                {"role": "system", "content": "\n".join(system_parts)},
                {"role": "user", "content": "\n".join(user_parts)},
            ],
        )
        return response.choices[0].message.content or ""

    def post(self, shared, prep_res, exec_res):
        if exec_res is None:
            return "default"
        shared["strategic_response"] = exec_res
        shared["response_type"] = "strategic"
        _emit(shared, "thinking", "Synthèse stratégique terminée.")
        return "default"


class _SemanticResolverNode(PFNode):
    """Runs before SQL generation to resolve fuzzy entity names to exact values.

    When the user query mentions specific names (e.g. "Marrakech", "France",
    "Aéroport Mohamed V"), this node:
    1. Uses the LLM to extract entity mentions.
    2. Runs ``SemanticSearchNode`` against all ``_distinct.parquet`` files.
    3. Injects the matched exact values into ``shared["prior_response_data"]``
       so the SQL generator uses correct filter values.
    """

    def prep(self, shared):
        _emit(shared, "thinking", "Analyse de la requête pour détecter les entités…")
        query = shared.get("query", "")
        parquet_dir = Path(
            shared.get("parquet_cache_dir")
            or str(pydantic_settings.parquet_cache_dir)
        )

        model_name = shared.get("embedding_model", DEFAULT_EMBEDDING_MODEL)
        model_instance = shared.get("embedding_model_instance")
        if model_instance is None:
            try:
                from main import app
                model_instance = getattr(app.state, "embedding_model", None)
            except Exception:
                pass
        if model_instance is None:
            from services.embedding_model_provider import get_embedding_model
            _emit(shared, "thinking", "Chargement du modèle d'embeddings…")
            model_instance = get_embedding_model(model_name)
        else:
            logger.info("Reusing pre-loaded SentenceTransformer model")
        shared["embedding_model_instance"] = model_instance

        return {
            "query": query,
            "parquet_dir": parquet_dir,
            "model_instance": model_instance,
            "shared_ref": shared,
        }

    def exec(self, prep_res):
        query = prep_res["query"]
        parquet_dir = prep_res["parquet_dir"]
        model_instance = prep_res["model_instance"]
        shared_ref = prep_res["shared_ref"]

        entities = _extract_entities(query)
        if not entities:
            _emit(shared_ref, "thinking", "Aucune entité spécifique détectée — passage à la génération SQL.")
            logger.info("No specific entities detected in query — skipping semantic search")
            return {"entities": [], "matches": []}

        entity_names = [e["text"] for e in entities]
        _emit(shared_ref, "thinking",
              f"{len(entities)} entité(s) détectée(s) : {', '.join(entity_names)}. "
              "Recherche de correspondances exactes…")
        logger.info("Detected %d entity mention(s): %s", len(entities), entity_names)

        distinct_files = _discover_distinct_parquets(parquet_dir)
        if not distinct_files:
            logger.warning("No _distinct.parquet files found in %s", parquet_dir)
            return {"entities": entities, "matches": []}

        all_matches: List[Dict[str, Any]] = []
        search_node = SemanticSearchNode()

        for entity in entities:
            entity_text = entity["text"]
            for dist_path in distinct_files:
                search_shared: Dict[str, Any] = {
                    "semantic_query": entity_text,
                    "distinct_parquet_path": str(dist_path),
                    "semantic_top_k": _SEMANTIC_TOP_K,
                    "semantic_threshold": _SEMANTIC_SIMILARITY_THRESHOLD,
                    "embedding_model_instance": model_instance,
                }
                try:
                    p = search_node.prep(search_shared)
                    r = search_node.exec(p)
                    search_node.post(search_shared, p, r)
                except Exception as exc:
                    logger.warning("Semantic search failed for '%s' on %s: %s",
                                   entity_text, dist_path.name, exc)
                    continue

                for match in search_shared.get("semantic_results", []):
                    enriched = {
                        "entity_query": entity_text,
                        "source_file": dist_path.stem,
                        **match,
                    }
                    all_matches.append(enriched)
                    _emit(shared_ref, "semantic_match",
                          f"« {entity_text} » → {match.get('distinct_value')} "
                          f"(colonne : {match.get('column_name')}, score : {match.get('score', 0):.3f})",
                          enriched)

        all_matches.sort(key=lambda m: m.get("score", 0), reverse=True)
        if all_matches:
            _emit(shared_ref, "thinking",
                  f"{len(all_matches)} correspondance(s) trouvée(s) dans les données.")
        logger.info("Semantic resolution found %d total match(es)", len(all_matches))
        return {"entities": entities, "matches": all_matches}

    def post(self, shared, prep_res, exec_res):
        matches = exec_res.get("matches", [])
        shared["semantic_results"] = matches

        if not matches:
            return "default"

        grouped: Dict[str, List[Dict[str, Any]]] = {}
        for m in matches:
            key = f"{m.get('column_name', '?')} ({m.get('source_file', '?')})"
            grouped.setdefault(key, []).append(m)

        lines = [
            "## Semantic entity resolution",
            "The following exact categorical values were matched from the embedded data. "
            "Use these **exact** values (not approximate spellings) in SQL WHERE clauses.\n",
        ]
        for col_key, col_matches in grouped.items():
            lines.append(f"### {col_key}")
            for m in col_matches[:_SEMANTIC_TOP_K]:
                score = m.get("score", 0)
                val = m.get("distinct_value", "")
                defs = m.get("definition_values", [])
                lines.append(f"  - **{val}** (similarity={score:.3f})")
                if defs:
                    lines.append(f"    aliases/definitions: {', '.join(str(d) for d in defs)}")
            lines.append("")

        context_block = "\n".join(lines)

        shared["_semantic_context"] = context_block

        existing_prior = shared.get("prior_response_data") or ""
        if existing_prior:
            shared["prior_response_data"] = f"{existing_prior}\n\n{context_block}"
        else:
            shared["prior_response_data"] = context_block

        logger.info("Injected %d semantic match(es) into prior_response_data", len(matches))
        return "default"


class _StreamingSQLGenerationNode(SQLGenerationNode):
    """SQLGenerationNode with stream_callback hooks."""

    def prep(self, shared):
        iteration = shared.get("iteration_count", 1)
        if iteration > 1:
            _emit(shared, "thinking", f"Affinement des requêtes SQL (itération {iteration})…")
        else:
            _emit(shared, "thinking", "Génération des requêtes SQL…")

        # For strategic queries, inject data hint so LLM generates data-fetching SQL
        if shared.get("query_type") == "strategic" and iteration == 1:
            hint = shared.get("strategic_data_hint", "")
            if hint:
                existing = shared.get("prior_response_data") or ""
                data_guidance = (
                    "## Contexte : requête stratégique\n"
                    "L'utilisateur pose une question stratégique. Génère des requêtes SQL "
                    "pour collecter les **données chiffrées** nécessaires à l'analyse.\n"
                    "Ne génère PAS de texte narratif — uniquement du SQL.\n\n"
                    f"Données nécessaires : {hint}"
                )
                if existing:
                    shared["prior_response_data"] = f"{existing}\n\n{data_guidance}"
                else:
                    shared["prior_response_data"] = data_guidance

        # Skip expensive conversation memory LLM call on first iteration (no history)
        orig_use_memory = self._use_memory
        if iteration == 1:
            self._use_memory = False

        result = super().prep(shared)
        self._use_memory = orig_use_memory
        return result

    def post(self, shared, prep_result, exec_result):
        action = super().post(shared, prep_result, exec_result)

        if action == "error":
            _emit(shared, "error",
                  f"Échec de la génération SQL : {shared.get('sql_generation_error', 'inconnu')}")
        elif action == "empty":
            _emit(shared, "error", "Aucune requête SQL n'a pu être générée.")
        else:
            queries = shared.get("sql_queries", [])
            for q in queries:
                _emit(shared, "sql_generated",
                      f"Requête : {q.get('label', 'Sans nom')}",
                      {"label": q.get("label"), "sql": q.get("sql", "")})

        return action


class _StreamingSQLExecutionNode(SQLExecutionNode):
    """SQLExecutionNode with stream_callback hooks."""

    def prep(self, shared):
        query_count = len(shared.get("sql_queries", []))
        _emit(shared, "thinking", f"Exécution de {query_count} requête{'s' if query_count > 1 else ''} SQL…")
        return super().prep(shared)

    def post(self, shared, prep_result, exec_result):
        action = super().post(shared, prep_result, exec_result)

        results = shared.get("sql_results", [])
        for r in results:
            label = r.get("label", "Requête")
            if r.get("error"):
                _emit(shared, "sql_result", f"{label} : Erreur — {r['error']}",
                      {"label": label, "error": r["error"]})
            else:
                row_count = r.get("row_count", 0)
                cols = len(r.get("columns", []))
                duration = r.get("duration_ms", 0)
                _emit(shared, "sql_result",
                      f"{label} : {row_count} ligne{'s' if row_count > 1 else ''} × {cols} colonne{'s' if cols > 1 else ''} [{duration}ms]",
                      {"label": label, "row_count": row_count, "columns": r.get("columns", []),
                       "duration_ms": duration, "truncated": r.get("truncated", False)})

        if action == "error":
            _emit(shared, "error", "Toutes les requêtes ont échoué ou retourné des résultats vides.")

        return action


class _StreamingEvaluationNode(ResponseEvaluationNode):
    """ResponseEvaluationNode with stream_callback hooks."""

    def prep(self, shared):
        _emit(shared, "thinking", "Évaluation de la qualité de la réponse…")
        return super().prep(shared)

    def post(self, shared, prep_result, exec_result):
        action = super().post(shared, prep_result, exec_result)

        ev = shared.get("evaluation", {})
        score = ev.get("precision_score", 0)
        verdict = ev.get("verdict", "n/a")
        justification = ev.get("justification", "")

        _emit(shared, "evaluation",
              f"Score : {score:.2f} ({verdict}) — {justification}",
              {"precision_score": score, "verdict": verdict,
               "justification": justification,
               "missing": ev.get("missing", []),
               "suggestions": ev.get("suggestions", [])})

        return action


class _RefineGuardNode(PFNode):
    """Bridge between evaluation (insufficient) and the next generation loop.

    Responsibilities:
    - Track iteration count and enforce max-iterations.
    - Inject evaluation feedback (missing items, suggestions) into
      ``prior_response_data`` so ``SQLGenerationNode`` sees them.
    - Record iteration history for observability.
    """

    def prep(self, shared):
        return {
            "evaluation": shared.get("evaluation", {}),
            "iteration_count": shared.get("iteration_count", 1),
            "max_iterations": shared.get("max_iterations", _DEFAULT_MAX_ITERATIONS),
        }

    def exec(self, prep_res):
        return prep_res

    def post(self, shared, prep_res, exec_res):
        evaluation = exec_res["evaluation"]
        iteration = exec_res["iteration_count"]
        max_iter = exec_res["max_iterations"]

        history: List[Dict[str, Any]] = shared.get("iteration_history", [])
        history.append({
            "iteration": iteration,
            "score": evaluation.get("precision_score", 0),
            "verdict": evaluation.get("verdict", ""),
            "missing": evaluation.get("missing", []),
        })
        shared["iteration_history"] = history

        next_iteration = iteration + 1
        shared["iteration_count"] = next_iteration

        # For strategic queries, we only need "enough data" — the strategic node
        # will synthesize the answer. Skip refinement if we have useful results.
        query_type = shared.get("query_type", "data_query")
        if query_type == "strategic":
            sql_results = shared.get("sql_results", [])
            has_data = any(
                r.get("row_count", 0) > 0 and not r.get("error")
                for r in sql_results
            )
            if has_data:
                logger.info(
                    "Strategic query: data collected (iteration %d, score=%.2f). "
                    "Proceeding to strategic synthesis.",
                    iteration, evaluation.get("precision_score", 0),
                )
                _emit(shared, "thinking",
                      "Données suffisantes collectées — passage à la synthèse stratégique…")
                return "max_reached"

        if next_iteration > max_iter:
            logger.warning(
                "Max iterations reached (%d). Stopping with score=%.2f",
                max_iter, evaluation.get("precision_score", 0),
            )
            _emit(shared, "thinking",
                  f"Nombre maximum d'itérations atteint ({max_iter}). "
                  f"Score final : {evaluation.get('precision_score', 0):.2f}.")
            return "max_reached"

        current_score = evaluation.get("precision_score", 0)
        if len(history) >= 2:
            prev_score = history[-2].get("score", 0)
            if abs(current_score - prev_score) <= _SCORE_PLATEAU_TOLERANCE:
                logger.warning(
                    "Score plateau detected (%.2f → %.2f, Δ≤%.2f). "
                    "Stopping early at iteration %d.",
                    prev_score, current_score, _SCORE_PLATEAU_TOLERANCE, iteration,
                )
                _emit(shared, "thinking",
                      f"Score stable ({prev_score:.2f} → {current_score:.2f}). "
                      "Arrêt anticipé — l'affinement n'améliore plus les résultats.")
                return "max_reached"

        feedback_parts: List[str] = []

        justification = evaluation.get("justification", "")
        if justification:
            feedback_parts.append(f"Previous evaluation: {justification}")

        missing = evaluation.get("missing", [])
        if missing:
            feedback_parts.append("Missing aspects:\n" + "\n".join(f"  - {m}" for m in missing))

        suggestions = evaluation.get("suggestions", [])
        if suggestions:
            feedback_parts.append("Suggestions:\n" + "\n".join(f"  - {s}" for s in suggestions))

        if feedback_parts:
            feedback_text = "\n\n".join(feedback_parts)
            semantic_ctx = shared.get("_semantic_context", "")
            if semantic_ctx:
                shared["prior_response_data"] = f"{semantic_ctx}\n\n{feedback_text}"
            else:
                shared["prior_response_data"] = feedback_text

        _emit(shared, "iteration",
              f"Itération {iteration} — score {evaluation.get('precision_score', 0):.2f} "
              f"({evaluation.get('verdict', '?')}). Affinement en cours…",
              {"iteration": iteration, "max_iterations": max_iter,
               "score": evaluation.get("precision_score", 0),
               "verdict": evaluation.get("verdict", "")})

        logger.info(
            "Iteration %d → score=%.2f, retrying (max=%d)",
            iteration, evaluation.get("precision_score", 0), max_iter,
        )
        return "retry"


class _FlowEndNode(PFNode):
    """Terminal node — records final iteration count and streams final results."""

    def post(self, shared, prep_res, exec_res):
        response_type = shared.get("response_type", "data_query")

        if response_type in ("strategic", "knowledge_only"):
            strategic_response = shared.get("strategic_response", "")
            ev = shared.get("evaluation", {})
            queries = shared.get("sql_queries", [])
            results = shared.get("sql_results", [])

            _emit(shared, "complete",
                  "Analyse stratégique terminée." if response_type == "strategic"
                  else "Réponse basée sur l'expertise métier.",
                  {
                      "response_type": response_type,
                      "strategic_response": strategic_response,
                      "iteration_count": shared.get("iteration_count", 1),
                      "evaluation": ev,
                      "sql_results_summary": shared.get("sql_results_summary", ""),
                      "sql_queries": [{"label": q.get("label"), "sql": q.get("sql")} for q in queries],
                      "sql_results": [
                          {
                              "label": r.get("label"),
                              "columns": r.get("columns", []),
                              "row_count": r.get("row_count", 0),
                              "rows": r.get("rows", [])[:20],
                              "error": r.get("error"),
                          }
                          for r in results
                      ],
                  })
            return "default"

        # Standard data_query path
        if "iteration_count" not in shared:
            shared["iteration_count"] = 1
        history = shared.get("iteration_history", [])
        evaluation = shared.get("evaluation", {})
        if not history or history[-1].get("iteration") != shared["iteration_count"]:
            history.append({
                "iteration": shared["iteration_count"],
                "score": evaluation.get("precision_score", 0),
                "verdict": evaluation.get("verdict", ""),
            })
            shared["iteration_history"] = history

        ev = shared.get("evaluation", {})
        summary = shared.get("sql_results_summary", "")
        queries = shared.get("sql_queries", [])
        results = shared.get("sql_results", [])

        _emit(shared, "complete",
              f"Terminé — {len(queries)} requête{'s' if len(queries) != 1 else ''}, "
              f"score : {ev.get('precision_score', 0):.2f} ({ev.get('verdict', 'n/a')}), "
              f"{shared.get('iteration_count', 1)} itération(s).",
              {
                  "response_type": "data_query",
                  "iteration_count": shared.get("iteration_count", 1),
                  "evaluation": ev,
                  "sql_results_summary": summary,
                  "sql_queries": [{"label": q.get("label"), "sql": q.get("sql")} for q in queries],
                  "sql_results": [
                      {
                          "label": r.get("label"),
                          "columns": r.get("columns", []),
                          "row_count": r.get("row_count", 0),
                          "rows": r.get("rows", [])[:20],
                          "error": r.get("error"),
                      }
                      for r in results
                  ],
              })

        return "default"


# ---------------------------------------------------------------------------
# Semantic Query Cache Nodes
# ---------------------------------------------------------------------------

class _QueryCacheLookupNode(PFNode):
    """Check the semantic query cache before hitting the LLM.

    If a cache hit is found, populate ``sql_results`` / ``sql_queries`` and
    return ``"cache_hit"`` to skip generation + execution.
    """

    def exec(self, _):
        return None

    def post(self, shared, prep_res, exec_res):
        cache = get_query_cache()
        if cache is None:
            return "default"

        query = shared.get("query", "")
        if not query:
            return "default"

        cb = shared.get("stream_callback")
        if cb:
            cb("thinking", "Recherche dans le cache sémantique…", None)

        hit = cache.lookup(query)
        if hit is not None:
            shared["sql_results"] = hit.results
            shared["sql_queries"] = hit.sql
            shared["cache_hit"] = True
            shared["cache_similarity"] = hit.similarity
            if cb:
                cb("thinking", f"Cache hit (similarité {hit.similarity:.2f})", {"cache_hit": True})
            logger.info(
                "[query_cache] HIT for '%s' (sim=%.3f)",
                query[:60], hit.similarity,
            )
            return "cache_hit"

        return "default"


class _QueryCacheStoreNode(PFNode):
    """Store a successful query + result in the semantic cache.

    Only stores if the query was NOT already a cache hit and returned data.
    """

    def exec(self, _):
        return None

    def post(self, shared, prep_res, exec_res):
        if shared.get("cache_hit"):
            return "default"

        cache = get_query_cache()
        if cache is None:
            return "default"

        results = shared.get("sql_results", [])
        queries = shared.get("sql_queries", [])
        query = shared.get("query", "")

        has_data = any(r.get("row_count", 0) > 0 for r in results)
        has_error = any(r.get("error") for r in results)

        if has_data and not has_error and query:
            source_ids = list(set(
                q.get("source_id", "duckdb") for q in queries
            ))
            cache.store(
                query=query,
                sql=queries,
                results=results,
                source_ids=source_ids,
            )

        return "default"


def create_sql_thinking_flow(
    *,
    threshold: float = _DEFAULT_THRESHOLD,
    max_iterations: int = _DEFAULT_MAX_ITERATIONS,
    use_memory: bool = True,
) -> Flow:
    """Assemble the iterative SQL thinking flow with query classification.

    Flow graph:
    ```
    classifier ──"data_query"──▶ semantic ──▶ sql_gen ──▶ sql_exec ──▶ evaluator ──▶ flow_end
       │                                                                  │
       │                                                          "insufficient"
       │                                                                  │
       │                                                          refine_guard
       │                                                           ↓        ↓
       │                                                      "retry"→sql_gen  "max_reached"→flow_end
       │
       ├─"knowledge_only"──▶ knowledge_node ──▶ flow_end
       │
       └─ (strategic queries use "data_query" path, then strategic_node before flow_end)
    ```

    For "strategic" queries, the evaluator routes to strategic_node before flow_end.

    Args:
        threshold: Minimum evaluation score to accept (0.0–1.0).
        max_iterations: Maximum generate→execute→evaluate loops.
        use_memory: Enable conversation memory in SQLGenerationNode.

    Returns:
        A PocketFlow Flow.
    """
    classifier = _QueryClassifierNode()
    knowledge_node = _KnowledgeOnlyNode()
    semantic = _SemanticResolverNode()
    cache_lookup = _QueryCacheLookupNode()
    sql_gen = _StreamingSQLGenerationNode(use_memory=use_memory)
    sql_exec = _StreamingSQLExecutionNode()
    cache_store = _QueryCacheStoreNode()
    evaluator = _StreamingEvaluationNode(threshold=threshold)
    refine_guard = _RefineGuardNode()
    strategic_node = _StrategicResponseNode()
    flow_end = _FlowEndNode()

    # Main data path: classifier → semantic → cache_lookup → sql_gen → sql_exec → cache_store → evaluator
    classifier - "data_query" >> semantic
    semantic >> cache_lookup
    cache_lookup >> sql_gen >> sql_exec >> cache_store >> evaluator

    # Cache hit → skip generation/execution, go straight to strategic response
    cache_lookup - "cache_hit" >> strategic_node

    # After evaluation succeeds → check if strategic synthesis needed
    evaluator >> strategic_node >> flow_end
    evaluator - "insufficient" >> refine_guard

    # SQL generation errors
    sql_gen - "error" >> strategic_node
    sql_gen - "empty" >> strategic_node
    sql_exec - "error" >> strategic_node

    # Refine loop
    refine_guard - "retry" >> sql_gen
    refine_guard - "max_reached" >> strategic_node

    # Knowledge-only path (no SQL needed)
    classifier - "knowledge_only" >> knowledge_node >> flow_end

    return Flow(start=classifier)


def run_sql_thinking(
    query: str,
    *,
    session_id: str = "default",
    threshold: float = _DEFAULT_THRESHOLD,
    max_iterations: int = _DEFAULT_MAX_ITERATIONS,
    use_memory: bool = True,
    stream_callback: Optional[StreamCallback] = None,
    prior_response_data: Any = None,
    sql_results: Optional[List[Dict[str, Any]]] = None,
    parquet_cache_dir: Optional[str] = None,
    connector_manager: Any = None,
) -> Dict[str, Any]:
    """Run the full SQL thinking pipeline.

    Args:
        query: Natural-language question.
        session_id: Conversation session id.
        threshold: Minimum precision score to accept.
        max_iterations: Maximum loops before giving up.
        use_memory: Enable conversation memory.
        stream_callback: Optional callback ``(event, message, data)`` for
            real-time streaming of the thinking process.
        prior_response_data: Seed context from prior interaction.
        sql_results: Seed results from prior execution.
        parquet_cache_dir: Override parquet directory.

    Returns:
        The shared-state dict after the flow completes.
    """
    flow = create_sql_thinking_flow(
        threshold=threshold,
        max_iterations=max_iterations,
        use_memory=use_memory,
    )

    skills = load_skill_definitions()
    skills_context = build_selected_skills_context(skills, include_full_content=False) if skills else ""
    if skills:
        logger.info("Loaded %d skill(s) into SQL thinking flow: %s", len(skills), ", ".join(s.name for s in skills))
    else:
        logger.warning("No skills found — flow will run without domain expertise context")

    shared: Dict[str, Any] = {
        "query": query,
        "session_id": session_id,
        "max_iterations": max_iterations,
        "evaluation_threshold": threshold,
        "iteration_count": 1,
        "iteration_history": [],
        "skills_context": skills_context,
    }
    if stream_callback is not None:
        shared["stream_callback"] = stream_callback
    if prior_response_data is not None:
        shared["prior_response_data"] = prior_response_data
    if sql_results is not None:
        shared["sql_results"] = sql_results
    if parquet_cache_dir is not None:
        shared["parquet_cache_dir"] = parquet_cache_dir
    if connector_manager is not None:
        shared["connector_manager"] = connector_manager

    logger.info("Starting SQL thinking flow: %s (threshold=%.2f, max_iter=%d)", query[:80], threshold, max_iterations)
    flow.run(shared)

    final_eval = shared.get("evaluation", {})
    iterations = shared.get("iteration_count", 1)
    logger.info(
        "SQL thinking flow complete: score=%.2f verdict=%s iterations=%d",
        final_eval.get("precision_score", 0),
        final_eval.get("verdict", "n/a"),
        iterations,
    )

    return shared


if __name__ == "__main__":
    import sys

    _COLORS = {
        "thinking":       "\033[36m",   # cyan
        "semantic_match": "\033[33m",   # yellow
        "sql_generated":  "\033[34m",   # blue
        "sql_result":     "\033[32m",   # green
        "evaluation":     "\033[35m",   # magenta
        "iteration":      "\033[33m",   # yellow
        "complete":       "\033[1;32m", # bold green
        "error":          "\033[1;31m", # bold red
    }
    _RESET = "\033[0m"

    def on_stream(event: str, message: str, data: Optional[Dict[str, Any]] = None) -> None:
        color = _COLORS.get(event, "")
        prefix = f"[{event}]"
        print(f"{color}{prefix:20s}{_RESET} {message}")

    query = (
        sys.argv[1] if len(sys.argv) > 1
        else "donne les chiffres par ans"
    )

    print(f"\nQuery: {query}\n")

    result = run_sql_thinking(
        query=query,
        threshold=0.7,
        max_iterations=3,
        use_memory=False,
        stream_callback=on_stream,
    )
