"""Low-level SQL helpers shared by ``BlockValidateNode`` and
``ReportSqlBatchNode``.

The reporting flow encodes the user's strict requirement that **every**
block (scalar, section, condition, narrative, chart_array, or composite
``mixed``) is backed by a CTE-shaped SQL query.  This module is the single
source of truth for what "CTE-shaped" means and for how to compose the
shared accounting / block libraries into per-block SQL.

Public surface
──────────────
* :func:`expand_includes`   — optionally injects missing accounting-library
  ``{{include: …}}`` stubs from ``index.yaml`` (transitive ``depends_on``),
  then inlines those references from the shared accounting / block libraries.
* :func:`parse_sql`         — parse via ``sqlglot`` (duckdb dialect),
  raising a structured error on parse failure.
* :func:`validate_block`    — enforce the per-kind projection contract for
  one block (or each sub-CTE of a ``mixed`` block) documented in
  ``data/reporting/SCHEMA.md``.
* :func:`validate_blocks`   — fan out :func:`validate_block` over every
  entry in ``definitions['blocks']``.
* :func:`field_param_names` — discover the ``$param`` references in a SQL
  string (used to bind values at run time).

The validator returns a *list of human-readable error strings* per block
so the agent can surface them to the user verbatim.  We don't raise mid-
validation: the caller decides whether to abort or continue.
"""

from __future__ import annotations

import re
from collections import defaultdict
from dataclasses import dataclass, field
from pathlib import Path
from typing import Any, Callable, Dict, List, Optional, Sequence, Set, Tuple

import sqlglot
import yaml
from sqlglot import exp


# ── Field kinds & projection contracts ──────────────────────────────────────

VALID_KINDS: Tuple[str, ...] = (
    "scalar",
    "section",
    "condition",
    "narrative",
    "chart_array",
)

# Block-level kinds.  ``mixed`` is a *composite* block whose YAML carries a
# ``ctes:`` list — each entry is then validated as one of the leaf kinds
# (scalar / section / condition / narrative / chart_array).  ``empty``
# blocks have no DSL inside them and are skipped by the validator.
VALID_BLOCK_KINDS: Tuple[str, ...] = (
    "scalar",
    "section",
    "condition",
    "narrative",
    "chart_array",
    "mixed",
    "empty",
    # Auto-generated by nodes/reporting/dto_source_generator.py — wraps a
    # parquet read with the DTO's canonical projection. Block authors point
    # their own CTE at one of these via FROM dto_<stem>.
    "source",
)

# Tokens that mark a parameter inside a CTE — DuckDB rewrites ``$name`` as
# ``:name`` once parsed; we accept either at validate time.
_RE_PARAM      = re.compile(r"\$([A-Za-z_][A-Za-z0-9_]*)")
_RE_INCLUDE    = re.compile(r"\{\{\s*include\s*:\s*([A-Za-z_][A-Za-z0-9_]*)\s*\}\}")
# ``FROM foo`` / ``JOIN foo`` where *foo* is an accounting library CTE name.
_RE_FROM_JOIN_TABLE = re.compile(
    r"\b(?:FROM|JOIN)\s+([A-Za-z_][A-Za-z0-9_]*)\b",
    re.IGNORECASE,
)

# (index_path, mtime_ns) → (deps_map, known_names, lower→canonical)
_ACCOUNTING_INDEX_CACHE: Dict[Tuple[str, int], Tuple[Dict[str, List[str]], Set[str], Dict[str, str]]] = {}


def _load_accounting_index_bundle(
    library_dir: Path,
) -> Optional[Tuple[Dict[str, List[str]], Set[str], Dict[str, str]]]:
    """Parse ``accounting/index.yaml`` once per mtime; return deps + name maps."""
    index_path = library_dir / "index.yaml"
    if not index_path.is_file():
        return None
    try:
        mtime = index_path.stat().st_mtime_ns
    except OSError:
        return None
    key = (str(index_path.resolve()), mtime)
    cached = _ACCOUNTING_INDEX_CACHE.get(key)
    if cached is not None:
        return cached

    doc = yaml.safe_load(index_path.read_text(encoding="utf-8")) or {}
    ctes = doc.get("ctes") or []
    deps_map: Dict[str, List[str]] = {}
    known: Set[str] = set()
    lower_to_canon: Dict[str, str] = {}
    for row in ctes:
        if not isinstance(row, dict):
            continue
        name = row.get("name")
        if not isinstance(name, str) or not name.strip():
            continue
        known.add(name)
        lower_to_canon[name.lower()] = name
        raw = row.get("depends_on") or []
        deps_map[name] = [d for d in raw if isinstance(d, str)]

    bundle = (deps_map, known, lower_to_canon)
    _ACCOUNTING_INDEX_CACHE[key] = bundle
    return bundle


def _closure_accounting_seeds(
    seeds: Set[str],
    deps_map: Dict[str, List[str]],
) -> Set[str]:
    """Transitive closure over ``depends_on`` (ancestors of every seed)."""
    out: Set[str] = set()
    stack = list(seeds)
    while stack:
        n = stack.pop()
        if n in out or n not in deps_map:
            continue
        out.add(n)
        for d in deps_map.get(n, ()):
            stack.append(d)
    return out


def _topo_sort_deps(nodes: Set[str], deps_map: Dict[str, List[str]]) -> List[str]:
    """Order *nodes* so every dependency appears before its dependents."""
    in_deg: Dict[str, int] = {n: 0 for n in nodes}
    rev: Dict[str, List[str]] = defaultdict(list)
    for n in nodes:
        for d in deps_map.get(n, ()):
            if d in nodes:
                in_deg[n] += 1
                rev[d].append(n)
    ready = sorted(n for n in nodes if in_deg[n] == 0)
    order: List[str] = []
    while ready:
        n = ready.pop(0)
        order.append(n)
        for m in sorted(rev.get(n, ())):
            in_deg[m] -= 1
            if in_deg[m] == 0:
                ready.append(m)
        ready.sort()
    if len(order) != len(nodes):
        return sorted(nodes)
    return order


def _merge_index_bundles(
    bundles: Sequence[Tuple[Dict[str, List[str]], Set[str], Dict[str, str]]],
) -> Tuple[Dict[str, List[str]], Set[str], Dict[str, str]]:
    """Merge several ``index.yaml`` bundles (accounting, insurance_production, …)."""
    if not bundles:
        return {}, set(), {}
    if len(bundles) == 1:
        return bundles[0][0], bundles[0][1], bundles[0][2]
    merged_deps: Dict[str, List[str]] = {}
    merged_known: Set[str] = set()
    merged_lower: Dict[str, str] = {}
    for deps_map, known, lower_to_canon in bundles:
        merged_known |= known
        for lk, canon in lower_to_canon.items():
            merged_lower.setdefault(lk, canon)
        for name, deps in deps_map.items():
            if name not in merged_deps:
                merged_deps[name] = list(deps)
            else:
                seen = set(merged_deps[name])
                for d in deps:
                    if d not in seen:
                        merged_deps[name].append(d)
                        seen.add(d)
    return merged_deps, merged_known, merged_lower


def _collect_reporting_index_dirs(
    library_dir: Optional[Path],
    merge_library_dirs: Optional[Sequence[Path]],
) -> List[Path]:
    """Directories whose ``index.yaml`` participates in dependency injection."""
    out: List[Path] = []
    seen: Set[str] = set()
    for d in ([library_dir] if library_dir else []) + list(merge_library_dirs or ()):
        if not d or not d.is_dir():
            continue
        key = str(d.resolve())
        if key in seen:
            continue
        if not (d / "index.yaml").is_file():
            continue
        seen.add(key)
        out.append(d)
    return out


def default_insurance_merge_library_dirs() -> List[Path]:
    """Optional ``insurance_production`` SQL library for reporting blocks."""
    root = Path(__file__).resolve().parent.parent.parent
    ins = root / "data" / "reporting" / "sql" / "insurance_production"
    return [ins] if (ins / "index.yaml").is_file() else []


def inject_accounting_dependencies(
    sql: str,
    library_dir: Optional[Path],
    *,
    merge_library_dirs: Optional[Sequence[Path]] = None,
) -> str:
    """Prefix a ``WITH`` query with missing ``{{include: …}}`` accounting stubs.

    When block SQL references a library CTE by name (``FROM revenue_total``)
    without inlining its ``depends_on`` chain, DuckDB fails because those
    relations are not real tables.  This helper reads
    ``<library_dir>/index.yaml``, discovers seeds from explicit includes plus
    ``FROM`` / ``JOIN`` hits against known CTE names, takes the transitive
    closure over ``depends_on``, topologically sorts it, and inserts
    ``{{include: dep}}, …`` immediately after the leading ``WITH`` for every
    dependency not already covered by an explicit ``{{include: …}}`` in the
    source string.

    No-op when no catalogue ``index.yaml`` is available or when there is nothing
    to inject.  Extra catalogues (e.g. ``insurance_production/index.yaml``) may be
    merged via *merge_library_dirs* so ``FROM period_metrics`` resolves together
    with ``FROM ledger``-style accounting atoms.

    If the SQL has no ``WITH`` clause, the string is returned unchanged.
    """
    if not isinstance(sql, str) or not sql.strip():
        return sql

    index_dirs = _collect_reporting_index_dirs(library_dir, merge_library_dirs)
    bundles: List[Tuple[Dict[str, List[str]], Set[str], Dict[str, str]]] = []
    for d in index_dirs:
        b = _load_accounting_index_bundle(d)
        if b:
            bundles.append(b)
    if not bundles:
        return sql

    deps_map, known, lower_to_canon = _merge_index_bundles(bundles)

    explicit: Set[str] = set()
    for m in _RE_INCLUDE.finditer(sql):
        raw = m.group(1)
        canon = lower_to_canon.get(raw.lower())
        if canon:
            explicit.add(canon)

    seeds: Set[str] = set(explicit)
    for m in _RE_FROM_JOIN_TABLE.finditer(sql):
        raw = m.group(1)
        canon = lower_to_canon.get(raw.lower())
        if canon:
            seeds.add(canon)

    if not seeds:
        return sql

    closure = _closure_accounting_seeds(seeds, deps_map)
    ordered = _topo_sort_deps(closure, deps_map)
    to_inject = [n for n in ordered if n not in explicit]
    if not to_inject:
        return sql

    frag = ", ".join(f"{{{{include: {n}}}}}" for n in to_inject)
    m_with = re.search(r"\bWITH\s+", sql, flags=re.IGNORECASE)
    if not m_with:
        return sql
    pos = m_with.end()
    rest = sql[pos:]
    return sql[:pos] + frag + ",\n     " + rest


# ── Include expansion ──────────────────────────────────────────────────────


class IncludeError(ValueError):
    """Raised when an ``{{include: <name>}}`` reference cannot be resolved."""


def _read_library_cte(library_dir: Path, name: str) -> str:
    """Read ``<library_dir>/<name>.sql``; strip leading ``WITH`` if present.

    Library files are stored as either:
      * ``WITH <name> AS ( … )``   — full CTE form, OR
      * ``<name> AS ( … )``        — inline form (preferred)

    Both work; we normalise to ``<name> AS ( … )``.
    """
    path = library_dir / f"{name}.sql"
    if not path.is_file():
        raise IncludeError(
            f"unknown include {name!r} (looked in {library_dir})"
        )
    text = path.read_text(encoding="utf-8").strip()
    # Drop leading WITH so the inlined chunk fits between commas.
    return re.sub(r"^\s*WITH\s+", "", text, count=1, flags=re.IGNORECASE)


def expand_includes(
    sql: str,
    library_dir: Optional[Path] = None,
    *,
    extra_library_dirs: Optional[Sequence[Path]] = None,
    merge_library_dirs: Optional[Sequence[Path]] = None,
    fragment_lookup: Optional[Callable[[str], Optional[str]]] = None,
    _seen: Optional[set] = None,
    _inner: bool = False,
) -> str:
    """Recursively inline ``{{include: <name>}}`` references.

    On the **outermost** call, if *library_dir* is the accounting tree (it
    contains ``index.yaml``), :func:`inject_accounting_dependencies` runs first
    so bare ``FROM library_cte`` references pull in transitive includes.

    Looks up each include name first in ``library_dir`` (the accounting
    atom library) then in any ``extra_library_dirs`` (typically the
        block-level CTE library at ``data/reporting/sql/fragment_library/``).  Cycles
    raise :class:`IncludeError`; an unknown name raises the same.  When
    neither library is configured, any ``{{include:…}}`` in the SQL is
    treated as an error so validation fails loudly.

    *merge_library_dirs* adds extra catalogues (e.g. ``insurance_production``)
    for both dependency injection and resolving ``{{include: …}}`` file paths.
    """
    # In graph mode (fragment_lookup set), the pickle graph is the single
    # source of truth — skip the disk-based accounting dependency injection.
    if not _inner and fragment_lookup is None:
        sql = inject_accounting_dependencies(
            sql, library_dir, merge_library_dirs=merge_library_dirs,
        )

    if "{{include:" not in sql and "{{ include:" not in sql:
        return sql

    candidate_dirs: List[Path] = []
    seen_dir: Set[str] = set()

    def _add_candidate(p: Optional[Path]) -> None:
        if p is None or not p.is_dir():
            return
        key = str(p.resolve())
        if key in seen_dir:
            return
        seen_dir.add(key)
        candidate_dirs.append(p)

    _add_candidate(library_dir)
    for extra in extra_library_dirs or ():
        _add_candidate(extra)
    for m in merge_library_dirs or ():
        _add_candidate(m)

    if not candidate_dirs and fragment_lookup is None:
        raise IncludeError(
            "SQL contains {{include: …}} but no CTE graph / library is configured"
        )

    seen = _seen if _seen is not None else set()

    def repl(m: re.Match) -> str:
        name = m.group(1)
        if name in seen:
            raise IncludeError(f"include cycle on {name!r}")

        chunk: Optional[str] = None
        # Graph-backed lookup wins (single source of truth for reports).
        if fragment_lookup is not None:
            found = fragment_lookup(name)
            if found is not None:
                chunk = re.sub(r"^\s*WITH\s+", "", found.strip(), count=1, flags=re.IGNORECASE)

        last_error: Optional[IncludeError] = None
        if chunk is None:
            for d in candidate_dirs:
                try:
                    chunk = _read_library_cte(d, name)
                    break
                except IncludeError as e:
                    last_error = e
        if chunk is None:
            raise last_error or IncludeError(
                f"unknown include {name!r} (not found in the CTE graph or any library)"
            )

        seen.add(name)
        try:
            return expand_includes(
                chunk,
                library_dir,
                extra_library_dirs=extra_library_dirs,
                merge_library_dirs=merge_library_dirs,
                fragment_lookup=fragment_lookup,
                _seen=seen,
                _inner=True,
            )
        finally:
            seen.discard(name)

    return _RE_INCLUDE.sub(repl, sql)


# ── Parsing ────────────────────────────────────────────────────────────────


@dataclass
class ParsedFieldSql:
    """Result of :func:`parse_sql` — *not* the AST itself, just the bits the
    validator and batch executor care about."""
    raw_sql:           str
    expanded_sql:      str
    select:            exp.Select
    cte_names:         List[str] = field(default_factory=list)
    final_aliases:     List[str] = field(default_factory=list)
    final_table_name:  Optional[str] = None
    has_with_clause:   bool = False
    referenced_params: List[str] = field(default_factory=list)


def field_param_names(sql: str) -> List[str]:
    """Return ``$name`` parameters referenced in *sql* in source order, deduped."""
    seen: set = set()
    out: List[str] = []
    for m in _RE_PARAM.finditer(sql):
        n = m.group(1)
        if n not in seen:
            seen.add(n)
            out.append(n)
    return out


def bind_params_case_insensitive(
    refs: Sequence[str],
    provided: Optional[Dict[str, Any]],
) -> Dict[str, Any]:
    """Build a DuckDB-ready ``{ref_name: value}`` dict from user input.

    DuckDB's parameter binding is case-sensitive — ``$REPORT_TITLE`` and
    ``$report_title`` are different placeholders to it.  But our shared
    parameter pool (in the UI and in agent prompts) canonicalizes names
    to lowercase so users don't have to retype the same value once for
    each casing convention used by their CTE authors.

    This helper bridges the two:

    * The returned dict's **keys** preserve the SQL's original case so
      DuckDB binds correctly.
    * **Values** are looked up in *provided* with an exact-case match
      first, then case-insensitively.  Missing keys map to ``None`` so
      callers can detect "unbound → NULL" warnings the same way they
      always have.

    Returning ``None`` (rather than omitting the key) is intentional:
    DuckDB requires every referenced placeholder to be bound, otherwise
    it raises ``Invalid Input Error``.
    """
    out: Dict[str, Any] = {}
    src = provided or {}
    if not refs:
        return out
    if not src:
        return {name: None for name in refs}
    lowered = {k.lower(): v for k, v in src.items()}
    for name in refs:
        if name in src:
            out[name] = src[name]
        else:
            out[name] = lowered.get(name.lower())
    return out


def parse_sql(
    sql: str,
    *,
    library_dir: Optional[Path] = None,
    extra_library_dirs: Optional[Sequence[Path]] = None,
    merge_library_dirs: Optional[Sequence[Path]] = None,
    dialect: str = "duckdb",
) -> ParsedFieldSql:
    """Expand ``{{include: …}}``, parse with ``sqlglot``, and return the
    bits we need for validation and execution.

    Raises :class:`IncludeError` for include problems and
    ``sqlglot.errors.ParseError`` if the expanded SQL doesn't parse.
    """
    expanded = expand_includes(
        sql, library_dir,
        extra_library_dirs=extra_library_dirs,
        merge_library_dirs=merge_library_dirs,
    )
    parsed = sqlglot.parse_one(expanded, read=dialect)

    if not isinstance(parsed, exp.Select):
        raise sqlglot.errors.ParseError(
            f"top-level statement is {type(parsed).__name__}, expected SELECT"
        )

    with_clause = parsed.args.get("with_") or parsed.args.get("with")
    cte_names: List[str] = []
    if with_clause is not None:
        cte_names = [c.alias_or_name for c in with_clause.expressions]

    final_aliases: List[str] = []
    for proj in parsed.expressions:
        alias = proj.alias_or_name
        final_aliases.append(alias if alias else "")

    final_from = parsed.find(exp.From)
    final_table_name: Optional[str] = None
    if final_from is not None:
        tbl = final_from.this
        if isinstance(tbl, exp.Table):
            final_table_name = tbl.name

    return ParsedFieldSql(
        raw_sql           = sql,
        expanded_sql      = expanded,
        select            = parsed,
        cte_names         = cte_names,
        final_aliases     = final_aliases,
        final_table_name  = final_table_name,
        has_with_clause   = with_clause is not None,
        referenced_params = field_param_names(sql),
    )


# ── Block-level validation ─────────────────────────────────────────────────
#
# A *block* is a tagged ``<element data-block="<name>">…</element>`` region
# of the template.  Each block is backed by **either**:
#
#   * an inline ``sql:`` (CTE-shaped, exactly one ``WITH … SELECT …``),
#   * a ``cte_ref:`` pointing to a row in
#     ``data/reporting/sql/fragment_library/index.yaml``, or
#   * (``mixed`` blocks only) a ``ctes:`` list whose entries are themselves
#     leaf-kind validatables.
#
# The projection contract per block kind, for the FINAL ``SELECT`` of the
# block (or each sub-CTE for mixed blocks), is documented in
# ``data/reporting/SCHEMA.md`` and re-derived in :func:`_block_kind_contract`.


def _expected_aliases_for_tokens(
    tokens: Sequence[str],
    mapping: Optional[Dict[str, str]] = None,
) -> List[str]:
    """Return the SQL column aliases expected for a block's tokens.

    The implicit rule is ``TOKEN → lowercase(TOKEN)``.  Any explicit
    override declared in ``mapping`` wins.  The returned list preserves
    the source order of ``tokens``.
    """
    out: List[str] = []
    seen: set = set()
    overrides = mapping or {}
    for tok in tokens:
        alias = overrides.get(tok) or tok.lower()
        if alias not in seen:
            seen.add(alias)
            out.append(alias)
    return out


def _validate_block_scalar(
    parsed: ParsedFieldSql,
    tokens: Sequence[str],
    mapping: Optional[Dict[str, str]],
) -> List[str]:
    """``scalar`` block → 1 row, 1 column per token (mapped or lowercased)."""
    errors: List[str] = []
    if not tokens:
        errors.append("scalar block must declare a non-empty tokens: list")
        return errors
    expected = _expected_aliases_for_tokens(tokens, mapping)
    actual = list(parsed.final_aliases)
    missing = [a for a in expected if a not in actual]
    if missing:
        errors.append(
            f"scalar block missing column alias(es) {missing!r} "
            f"(SELECT projects {actual!r}; expected superset of {expected!r})"
        )
    return errors


def _validate_block_section(
    parsed: ParsedFieldSql,
    tokens: Sequence[str],
    mapping: Optional[Dict[str, str]],
) -> List[str]:
    """``section`` block → N rows, one column per inner-section token."""
    return _validate_block_scalar(parsed, tokens, mapping)


def _validate_block_condition(parsed: ParsedFieldSql) -> List[str]:
    """``condition`` block → 1 row, 1 column aliased ``value``."""
    errors: List[str] = []
    if len(parsed.final_aliases) != 1:
        errors.append(
            f"condition block must project exactly 1 column, got "
            f"{len(parsed.final_aliases)}"
        )
        return errors
    if parsed.final_aliases[0] != "value":
        errors.append(
            f"condition block must alias its column AS value, got "
            f"{parsed.final_aliases[0]!r}"
        )
    return errors


def _validate_block_chart_array(parsed: ParsedFieldSql) -> List[str]:
    """``chart_array`` block → N rows, 1 column aliased ``value``."""
    return _validate_block_condition(parsed)


def _validate_block_narrative(
    parsed: ParsedFieldSql,
    grounding_fields: Sequence[str],
) -> List[str]:
    """``narrative`` block → 1 row, one column per grounding field."""
    errors: List[str] = []
    if not grounding_fields:
        errors.append(
            "narrative block must declare a non-empty grounding_fields: list"
        )
        return errors
    expected = list(grounding_fields)
    actual = list(parsed.final_aliases)
    missing = [a for a in expected if a not in actual]
    if missing:
        errors.append(
            f"narrative block missing column alias(es) {missing!r} "
            f"(SELECT projects {actual!r}; expected superset of {expected!r})"
        )
    return errors


def _validate_block_empty(parsed: ParsedFieldSql) -> List[str]:
    """``empty`` block → 1 row, 1 projected value injected into the block HTML."""
    errors: List[str] = []
    if len(parsed.final_aliases) != 1:
        errors.append(
            f"empty block must project exactly 1 column, got {len(parsed.final_aliases)}"
        )
    return errors


def _validate_block_source(parsed: ParsedFieldSql) -> List[str]:
    """``source`` block → DTO-generated parquet wrapper. Only structural checks.

    These CTEs are produced by ``dto_source_generator.generate_all_dto_sources``
    and consumed indirectly via ``FROM dto_<stem>`` references; they do not
    need to satisfy a projection contract because they're never rendered
    into the HTML directly.
    """
    return []


@dataclass
class BlockValidationReport:
    """Per-block outcome of :func:`validate_block`.

    ``sub_reports`` is populated for ``kind: mixed`` blocks — one entry
    per sub-CTE in the block's ``ctes:`` list, keyed by the sub-CTE id.
    """
    block_id:    str
    kind:        str
    ok:          bool
    errors:      List[str]                = field(default_factory=list)
    warnings:    List[str]                = field(default_factory=list)
    parsed:      Optional[ParsedFieldSql] = None
    sub_reports: List["BlockValidationReport"] = field(default_factory=list)


def _resolve_cte_ref(
    cte_ref: str,
    *,
    block_library_dir: Optional[Path],
) -> str:
    """Read ``<block_library_dir>/<cte_ref>.sql`` as the block's SQL.

    The block-CTE library is *required* when ``cte_ref`` is set; raises
    :class:`IncludeError` otherwise.
    """
    if block_library_dir is None or not block_library_dir.is_dir():
        raise IncludeError(
            f"cte_ref={cte_ref!r} but no fragment library (sql/fragment_library/) is configured"
        )
    path = block_library_dir / f"{cte_ref}.sql"
    if not path.is_file():
        raise IncludeError(
            f"cte_ref={cte_ref!r} not found in block library {block_library_dir}"
        )
    return path.read_text(encoding="utf-8")


def _validate_leaf_block(
    block_id:           str,
    kind:               str,
    sql:                str,
    *,
    tokens:             Sequence[str],
    mapping:            Optional[Dict[str, str]],
    grounding_fields:   Sequence[str],
    library_dir:        Optional[Path],
    block_library_dir:  Optional[Path],
    merge_library_dirs: Optional[Sequence[Path]],
    dialect:            str,
) -> BlockValidationReport:
    """Validate a *leaf* (non-mixed) block's resolved SQL against its kind."""
    report = BlockValidationReport(block_id=block_id, kind=kind, ok=True)

    if not isinstance(sql, str) or not sql.strip():
        report.ok = False
        report.errors.append(
            "every leaf block must resolve to a non-empty CTE-shaped SQL"
        )
        return report

    extra: List[Path] = []
    if block_library_dir is not None:
        extra.append(block_library_dir)
    try:
        parsed = parse_sql(
            sql,
            library_dir=library_dir,
            extra_library_dirs=extra,
            merge_library_dirs=merge_library_dirs,
            dialect=dialect,
        )
        report.parsed = parsed
    except IncludeError as e:
        report.ok = False
        report.errors.append(f"include error: {e}")
        return report
    except sqlglot.errors.ParseError as e:
        report.ok = False
        first = e.errors[0]["description"] if getattr(e, "errors", None) else str(e)
        report.errors.append(f"parse error: {first}")
        return report

    if not parsed.has_with_clause:
        report.errors.append(
            "block sql must be CTE-shaped: start with WITH <name> AS ( … )"
        )

    if (
        parsed.final_table_name
        and parsed.cte_names
        and parsed.final_table_name not in parsed.cte_names
    ):
        report.warnings.append(
            f"final SELECT reads FROM {parsed.final_table_name!r} "
            f"which is not one of the declared CTEs {parsed.cte_names!r}"
        )

    if kind == "scalar":
        report.errors.extend(_validate_block_scalar(parsed, tokens, mapping))
    elif kind == "section":
        report.errors.extend(_validate_block_section(parsed, tokens, mapping))
    elif kind == "condition":
        report.errors.extend(_validate_block_condition(parsed))
    elif kind == "chart_array":
        report.errors.extend(_validate_block_chart_array(parsed))
    elif kind == "narrative":
        report.errors.extend(_validate_block_narrative(parsed, grounding_fields))
    elif kind == "empty":
        report.errors.extend(_validate_block_empty(parsed))
    elif kind == "source":
        report.errors.extend(_validate_block_source(parsed))
    else:
        report.errors.append(f"leaf block kind {kind!r} is not validatable")

    report.ok = not report.errors
    return report


def validate_block(
    block:              Dict[str, Any],
    *,
    library_dir:        Optional[Path] = None,
    block_library_dir:  Optional[Path] = None,
    merge_library_dirs: Optional[Sequence[Path]] = None,
    dialect:            str            = "duckdb",
) -> BlockValidationReport:
    """Validate a single block dict from ``definitions.yaml.blocks``.

    Hard invariants (returned as errors, not raised):

    * ``kind`` must be one of :data:`VALID_BLOCK_KINDS`.
    * Exactly one of ``sql:`` or ``cte_ref:`` is set on a leaf block.
    * ``mixed`` blocks must declare a non-empty ``ctes:`` list whose
      entries are themselves valid leaf blocks.
    * If ``mapping:`` is present, every key must be a token declared in
      the block's ``tokens:`` list.

    The function never raises on user errors — they go into
    ``report.errors`` so the caller can surface every problem at once.
    Programming errors (bad input types) still raise.
    """
    bid: str = block.get("id") or "<unknown>"
    kind: str = (block.get("kind") or "").strip()
    report = BlockValidationReport(block_id=bid, kind=kind, ok=True)

    if kind not in VALID_BLOCK_KINDS:
        report.ok = False
        report.errors.append(
            f"kind {kind!r} is not one of {', '.join(VALID_BLOCK_KINDS)}"
        )
        return report

    tokens          = block.get("tokens")          or []
    mapping         = block.get("mapping")         or None
    grounding_fields= block.get("grounding_fields")or []

    if mapping and not isinstance(mapping, dict):
        report.ok = False
        report.errors.append(
            f"mapping: must be a dict, got {type(mapping).__name__}"
        )
        return report

    if mapping:
        unknown = [k for k in mapping.keys() if k not in tokens]
        if unknown:
            report.errors.append(
                f"mapping has key(s) not in tokens: {unknown!r}"
            )

    # ── Mixed block: recurse into ctes: ──────────────────────────────
    if kind == "mixed":
        ctes = block.get("ctes")
        if not isinstance(ctes, list) or not ctes:
            report.ok = False
            report.errors.append(
                "mixed block must declare a non-empty ctes: list"
            )
            return report
        for sub in ctes:
            if not isinstance(sub, dict):
                report.errors.append(
                    f"each entry of ctes: must be a mapping, got "
                    f"{type(sub).__name__}"
                )
                continue
            sub_id   = sub.get("id") or "<unknown>"
            sub_kind = (sub.get("kind") or "").strip()

            if sub_kind == "mixed":
                report.errors.append(
                    f"mixed sub-CTE {sub_id!r}: nested mixed blocks are not "
                    f"allowed (flatten into the parent)"
                )
                continue

            sub_sql_str: Optional[str] = None
            sub_cte_ref = sub.get("cte_ref")
            sub_sql = sub.get("sql")
            if sub_cte_ref and sub_sql:
                report.errors.append(
                    f"sub-CTE {sub_id!r}: set exactly one of sql or cte_ref"
                )
            elif sub_cte_ref:
                try:
                    sub_sql_str = _resolve_cte_ref(
                        sub_cte_ref, block_library_dir=block_library_dir,
                    )
                except IncludeError as e:
                    report.errors.append(
                        f"sub-CTE {sub_id!r}: {e}"
                    )
                    continue
            elif sub_sql:
                sub_sql_str = sub_sql
            else:
                report.errors.append(
                    f"sub-CTE {sub_id!r}: must declare either sql: or cte_ref:"
                )
                continue

            sub_report = _validate_leaf_block(
                block_id          = f"{bid}.{sub_id}",
                kind              = sub_kind,
                sql               = sub_sql_str or "",
                tokens            = sub.get("tokens") or [],
                mapping           = sub.get("mapping") or None,
                grounding_fields  = sub.get("grounding_fields") or [],
                library_dir       = library_dir,
                block_library_dir = block_library_dir,
                merge_library_dirs= merge_library_dirs,
                dialect           = dialect,
            )
            report.sub_reports.append(sub_report)
            if not sub_report.ok:
                report.errors.extend(
                    f"[sub-CTE {sub_id}] {e}" for e in sub_report.errors
                )
            report.warnings.extend(
                f"[sub-CTE {sub_id}] {w}" for w in sub_report.warnings
            )

        report.ok = not report.errors
        return report

    # ── Leaf block: resolve sql or cte_ref ───────────────────────────
    sql_inline = block.get("sql")
    cte_ref    = block.get("cte_ref")

    sql_resolved: Optional[str] = None
    if isinstance(sql_inline, str) and sql_inline.strip():
        sql_resolved = sql_inline.strip()
        if cte_ref:
            report.warnings.append(
                "both sql: and cte_ref: are set — sql: takes precedence; "
                "remove cte_ref to avoid confusion"
            )
    elif cte_ref:
        try:
            sql_resolved = _resolve_cte_ref(
                cte_ref, block_library_dir=block_library_dir,
            )
        except IncludeError as e:
            report.ok = False
            report.errors.append(str(e))
            return report
    else:
        report.ok = False
        report.errors.append(
            "leaf block must declare a non-empty sql: or a cte_ref:"
        )
        return report

    leaf_report = _validate_leaf_block(
        block_id          = bid,
        kind              = kind,
        sql               = sql_resolved,
        tokens            = tokens,
        mapping           = mapping,
        grounding_fields  = grounding_fields,
        library_dir       = library_dir,
        block_library_dir = block_library_dir,
        merge_library_dirs= merge_library_dirs,
        dialect           = dialect,
    )
    report.parsed = leaf_report.parsed
    report.errors.extend(leaf_report.errors)
    report.warnings.extend(leaf_report.warnings)
    report.ok = not report.errors
    return report


def validate_blocks(
    definitions: Dict[str, Any],
    *,
    library_dir:       Optional[Path] = None,
    block_library_dir: Optional[Path] = None,
    merge_library_dirs: Optional[Sequence[Path]] = None,
    dialect:           str            = "duckdb",
) -> List[BlockValidationReport]:
    """Validate every entry of ``definitions['blocks']`` in source order.

    Deprecated/empty blocks are skipped (no SQL to validate).  Returns
    one :class:`BlockValidationReport` per validated block.
    """
    blocks = definitions.get("blocks") or []
    if not isinstance(blocks, list):
        raise TypeError("definitions['blocks'] must be a list")

    reports: List[BlockValidationReport] = []
    for b in blocks:
        if not isinstance(b, dict):
            continue
        if b.get("deprecated"):
            continue
        reports.append(validate_block(
            b,
            library_dir=library_dir,
            block_library_dir=block_library_dir,
            merge_library_dirs=merge_library_dirs,
            dialect=dialect,
        ))
    return reports
